language: php

php:
  - 5.4
  - 5.5
  - 5.6

addons:
  postgresql: "9.3"

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - createuser -Upostgres -d -A -S -R vagrant
  - createdb -Uvagrant -E UTF-8 -T template0 app_test

script:
  - ./vendor/bin/phpunit
